import { StyleSheet } from "react-native";

export const loginStyles = StyleSheet.create({
  container: {
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: 480,
    width: "100%",
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 60,
    paddingBottom: 60,
    overflow: "hidden",
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100%',
  },
  logoContainer: {
    display: "flex",
    width: "100%",
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  logo: {
    aspectRatio: 0.71,
    width: 154,
    maxWidth: "100%",
  },
  welcomeContainer: {
    marginTop: 60,
    width: "100%",
    fontFamily: "Inter, -apple-system, Roboto, Helvetica, sans-serif",
  },
  helloText: {
    alignSelf: "stretch",
    width: "100%",
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    fontSize: 25,
    color: "rgba(68, 68, 68, 1)",
    fontWeight: "600",
  },
  welcomeText: {
    alignSelf: "stretch",
    width: "100%",
    paddingLeft: 10,
    paddingRight: 10,
    paddingBottom: 10,
    fontSize: 30,
    color: "rgba(140, 82, 255, 1)",
    fontWeight: "900",
  },
  formContainer: {
    marginTop: 40,
    width: "100%",
    fontFamily: "Inter, -apple-system, Roboto, Helvetica, sans-serif",
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  inputContainer: {
    display: "flex",
    minHeight: 28,
    width: "100%",
    marginBottom: 16,
    flexDirection: "column",
    alignItems: "stretch",
    fontSize: 15,
    color: "rgba(68, 68, 68, 1)",
    fontWeight: "400",
    justifyContent: "center",
  },
  inputLabel: {
    alignSelf: "stretch",
    flex: 1,
    flexShrink: 1,
    flexBasis: "0%",
    width: "100%",
    height: "100%",
  },
  inputText: {
    fontSize: 15,
    color: "rgba(68, 68, 68, 1)",
    fontWeight: "400",
  },
  textInput: {
    borderColor: "rgba(140, 82, 255, 0.3)",
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    fontFamily: "Inter, -apple-system, Roboto, Helvetica, sans-serif",
    color: "#333",
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginTop: 8,
  },
  inputBorder: {
    borderColor: "rgba(140, 82, 255, 1)",
    borderStyle: "solid",
    borderWidth: 1,
    minHeight: 1,
    marginTop: 10,
    width: "100%",
  },
  buttonContainer: {
    marginTop: 20,
    width: "100%",
  },
  loginButton: {
    borderRadius: 12,
    display: "flex",
    minHeight: 50,
    width: "100%",
    paddingVertical: 12,
    backgroundColor: "rgba(140, 82, 255, 1)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "rgba(140, 82, 255, 0.3)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    marginTop: 20,
  },

  loginButtonText: {
    fontSize: 20,
    color: "rgba(255, 255, 255, 1)",
    fontWeight: "600",
    textAlign: "center",
  },
  forgotPassword: {
    alignSelf: "stretch",
    marginTop: 10,
    width: "100%",
    fontSize: 15,
    color: "rgba(68, 68, 68, 1)",
    fontWeight: "400",
  },
  forgotPasswordText: {
    fontSize: 15,
    color: "rgba(68, 68, 68, 1)",
    fontWeight: "400",
    textAlign: "center",
  },
  socialContainer: {
    marginTop: 60,
    width: "100%",
  },
  dividerContainer: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    flexDirection: "row",
  },
  leftDivider: {
    flex: 1,
    flexShrink: 1,
    flexBasis: "0%",
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    justifyContent: "center",
  },
  dividerLine: {
    borderColor: "rgba(62, 62, 62, 1)",
    borderStyle: "solid",
    borderWidth: 1,
    minHeight: 1,
    width: "100%",
  },
  dividerText: {
    marginTop: 'auto',
    marginBottom: 'auto',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    fontFamily: 'Inter',
    fontSize: 13,
    color: '#888',
    fontWeight: '500',
    textAlign: 'center',
    flex: 1,
    flexShrink: 1,
    flexBasis: '0%',
    letterSpacing: 0.2,
  },
  rightDivider: {
    flex: 1,
    flexShrink: 1,
    flexBasis: "0%",
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    justifyContent: "center",
  },
  socialIconsContainer: {
    display: 'flex',
    marginTop: 10,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 40,
    justifyContent: 'center',
  },
  socialIconWrapper: {
    alignSelf: 'stretch',
    display: 'flex',
    marginTop: 'auto',
    marginBottom: 'auto',
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
    paddingBottom: 14,
    borderRadius: 50,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
    justifyContent: 'center',
  },
  socialIcon: {
    width: 40,
    height: 40,
  },
  signUpContainer: {
    marginTop: 20,
    width: "100%",
    textAlign: "center",
  },
  signUpText: {
    fontSize: 15,
    color: "rgba(68, 68, 68, 1)",
    fontWeight: "400",
    textAlign: "center",
  },
  signUpLink: {
    color: "rgba(140, 82, 255, 1)",
    fontWeight: "600",
  },
}); 